language: c

env:
 - RACKET_VERSION=5.3.5
 - RACKET_VERSION=5.3.6
 - RACKET_VERSION=HEAD

before_install:
 - curl https://raw.github.com/greghendershott/travis-racket/master/install-racket.sh | sh

install:

before_script:

script:
 - cd ..   # Travis did a cd into the dir. Back up, for the next:
 - /usr/racket/bin/raco pkg install --deps search-auto --link markdown
 - /usr/racket/bin/raco pkg show
 - /usr/racket/bin/raco test -x -p markdown

after_script:
